name: Blob storage website CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:            
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Install npm packages
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE
        npm install

    - name: Replace ENV tokens - PUBLIC_URL
      uses: TickX/var-to-dotenv@v1.1.1
      with:
        key: 'PUBLIC_URL'
        value: ${{ secrets.PUBLIC_URL }}
        envPath: '.env'
      
    - name: Replace ENV tokens - GOOGLE_ANALYTICS_ID
      uses: TickX/var-to-dotenv@v1.1.1
      with:
        key: 'GOOGLE_ANALYTICS_ID'
        value: ${{ secrets.GOOGLE_ANALYTICS_ID }}
        envPath: '.env'

    - name: Replace ENV tokens - GOOGLE_ADSENSE_CLIENT_ID
      uses: TickX/var-to-dotenv@v1.1.1
      with:
        key: 'GOOGLE_ADSENSE_CLIENT_ID'
        value: ${{ secrets.GOOGLE_ADSENSE_CLIENT_ID }}
        envPath: '.env'

    - name: Build app
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE
        npm run build

    - name: Publish app
      if: github.ref == 'refs/heads/master'
      uses: Azure/cli@v1.0.0
      with:
        azcliversion: latest
        inlineScript: |
          az storage blob upload-batch -s $GITHUB_WORKSPACE/build -d \$web --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }}

    - name: Purge CDN endpoint
      if: github.ref == 'refs/heads/master'
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "${{ secrets.AZURE_CDN_PROFILE }}" --name "${{ secrets.CDN_ENDPOINT }}" --resource-group "${{ secrets.AZURE_RESOURCE_GROUP }}"
           
  # Azure logout 
    - name: logout
      run: |
            az logout 
